Feat/dev share
siliconflow/web-kickstarter pull request #33
Opened 2024-03-19 07:54 UTC by Of-qinhai

1.fix chat open ai sdk ,fetch  post error bug
2.optimization sdk  config proxyUrl
3.optimization package.json

2024-03-19 10:02 UTC, wuzhuzhu commented on app/(protected)/models/text/[modelSubType]/[[...modelId]]/components/content.tsx
> +					<section className="chatbot-section flex flex-col origin:w-[800px] w-full  h-full rounded-md pl-2 md:pl-6">
这里写死宽度

2024-03-19 10:15 UTC, wuzhuzhu commented on app/api/chat/route.ts
> -	headers?: Record<string, string>;
这里代码是原封不动的示例吗？

2024-03-19 10:15 UTC, wuzhuzhu commented on app/globals.css
> +  .custom-scrollbar::-webkit-scrollbar {
暂时注释掉

2024-03-19 10:18 UTC, wuzhuzhu commented on components/shared/models/models-share.tsx
> +					<div className="relative w-fit [font-family:'Roboto-Regular',Helvetica] font-normal text-tokens-text-text-muted-foreground text-[14px] tracking-[0] leading-[24px] whitespace-nowrap">
css有问题 figma css不能无脑抄

2024-03-19 10:19 UTC, wuzhuzhu commented on components/shared/models/models-share.tsx
> +							<GrShareOption />
icon优先选fa

2024-03-19 10:20 UTC, wuzhuzhu commented on app/api/chat/route.ts
> -	headers?: Record<string, string>;
逻辑没有细看 如果是示例没有改动就这样吧

2024-03-19 10:32 UTC, Of-qinhai commented on app/api/chat/route.ts
> -	headers?: Record<string, string>;
我这没看到这段代码
nterface CustomClientOptions extends ClientOptions {
	headers?: Record<string, string>;

2024-03-19 10:33 UTC, Of-qinhai commented on components/shared/models/models-share.tsx
> +					<div className="relative w-fit [font-family:'Roboto-Regular',Helvetica] font-normal text-tokens-text-text-muted-foreground text-[14px] tracking-[0] leading-[24px] whitespace-nowrap">
<div className="flex justify-end items-center gap-2 relative">
					<div className="relative w-fit [font-family:'Roboto-Regular',Helvetica] font-normal text-tokens-text-text-muted-foreground text-sm tracking-[0] leading-6 whitespace-nowrap">
						Generated in {speed} seconds
					</div>

2024-03-20 09:51 UTC, wuzhuzhu requested changes

2024-03-20 09:51 UTC, wuzhuzhu commented on app/(protected)/keys/[[...pageNumber]]/page.tsx
> +import dynamic from "next/dynamic";
为什么要dynamic？

2024-03-20 09:51 UTC, wuzhuzhu commented on app/(protected)/models/text/[modelSubType]/[[...modelId]]/components/Bubble.tsx
>  									<path d="M10.3333 0.127197H7.66665V1.46053H10.3333C11.4333 1.46053 12.3333 2.36053 12.3333 3.46053C12.3333 4.56053 11.4333 5.46053 10.3333 5.46053H7.66665V6.79386H10.3333C12.1733 6.79386 13.
这是啥

2024-03-20 09:51 UTC, wuzhuzhu commented on app/(protected)/models/text/[modelSubType]/[[...modelId]]/components/content.tsx
> +									{isLoading ? "sending..." : "Send Message"}
Generating...
1. 大小写行为一致
2. 发送只占这个行为用时的小部分，不符合用户心智
3. 以后有取消了这个过渡时间按钮应该是Cancel，等同于chatgpt的方块符号

2024-03-20 09:51 UTC, wuzhuzhu commented on components/shared/models/models-share.tsx
> +									d="M3.5 5.00006C3.22386 5.00006 3 5.22392 3 5.50006L3 11.5001C3 11.7762 3.22386 12.0001 3.5 12.0001L11.5 12.0001C11.7761 12.0001 12 11.7762 12 11.5001L12 5.50006C12 5.22392 11.7761 5.00006 1
不要写死svg。用正常的引入方式

2024-03-20 09:51 UTC, wuzhuzhu commented on app/api/chat/route.ts
> +	const cookies = req.headers.getSetCookie();
这就是把cookie拆开又组合了一遍。
直接转发。

2024-03-20 09:51 UTC, wuzhuzhu commented on components/shared/server/pagination.tsx
> +		Math.min(Number(current) - 1 + pageNumLimit + 1, pageNumbers.length),
这边有点奇怪 待我再看下

2024-03-20 09:51 UTC, wuzhuzhu commented on app/(protected)/keys/[[...pageNumber]]/page.tsx
>  			<div className="flex w-full justify-end items-end">
日期格式化不对
1. 没考虑时区
2. 本身格式化也不对
3. 用datefns+其时区方案

2024-03-20 09:58 UTC, Of-qinhai commented on app/(protected)/keys/[[...pageNumber]]/page.tsx
> +import dynamic from "next/dynamic";
已删除，改为
import PaginationSection from "@/components/shared/server/pagination";

2024-03-20 10:01 UTC, Of-qinhai commented on app/(protected)/models/text/[modelSubType]/[[...modelId]]/components/Bubble.tsx
>  									<path d="M10.3333 0.127197H7.66665V1.46053H10.3333C11.4333 1.46053 12.3333 2.36053 12.3333 3.46053C12.3333 4.56053 11.4333 5.46053 10.3333 5.46053H7.66665V6.79386H10.3333C12.1733 6.79386 13.
已删

2024-03-20 10:03 UTC, Of-qinhai commented on components/shared/models/models-share.tsx
> +									d="M3.5 5.00006C3.22386 5.00006 3 5.22392 3 5.50006L3 11.5001C3 11.7762 3.22386 12.0001 3.5 12.0001L11.5 12.0001C11.7761 12.0001 12 11.7762 12 11.5001L12 5.50006C12 5.22392 11.7761 5.00006 1
已换

2024-03-20 10:07 UTC, Of-qinhai commented on app/(protected)/models/text/[modelSubType]/[[...modelId]]/components/content.tsx
> +									{isLoading ? "sending..." : "Send Message"}
1.我这已将sending 改为了Replying 。
2.cancel 等有了再说吧。

2024-03-20 10:08 UTC, Of-qinhai commented on components/shared/models/models-share.tsx
> +									d="M3.5 5.00006C3.22386 5.00006 3 5.22392 3 5.50006L3 11.5001C3 11.7762 3.22386 12.0001 3.5 12.0001L11.5 12.0001C11.7761 12.0001 12 11.7762 12 11.5001L12 5.50006C12 5.22392 11.7761 5.00006 1
这个在feat/dev-share里是注释了的，在feat/dev-share320分支提的pr里会修复，注释掉的代码请无视。

2024-03-21 02:46 UTC, Of-qinhai commented on app/(protected)/keys/[[...pageNumber]]/page.tsx
>  			<div className="flex w-full justify-end items-end">
分区格式化已加上，暂时只给了中美法3个时区的formart，如果还有其它时区的格式化的需求，请自行修改。

2024-03-21 03:11 UTC, merged