Feat/console
siliconflow/web-kickstarter pull request #48
Opened 2024-04-10 03:48 UTC by Of-qinhai

siliconflow新增console端

2024-04-10 07:29 UTC, wuzhuzhu commented on .vscode/settings.json
> +		"editor.defaultFormatter": "vscode.typescript-language-features"
这个被不小心改了哦

2024-04-10 08:00 UTC, wuzhuzhu commented on app/layout.tsx
> -		<html lang="en">
这个不太行吧，水合warning是必要的

2024-04-10 08:13 UTC, wuzhuzhu commented on package.json
> +    "use-debounce": "^10.0.0",
和已经引入的lodashes功能重叠了，用lodashes吧。注意不是lodash

2024-04-10 08:18 UTC, wuzhuzhu commented on package.json
> +    "next-themes": "^0.3.0",
delete~

2024-04-10 08:23 UTC, wuzhuzhu commented on components/console/layout/header.tsx
> +            <svg
我们的logo

2024-04-10 08:41 UTC, Of-qinhai commented on .vscode/settings.json
> +		"editor.defaultFormatter": "vscode.typescript-language-features"
已经换了，是不是需要在.gitignore 里加一下。。

2024-04-10 08:42 UTC, Of-qinhai commented on app/(console)/console/layout.tsx
> +export const metadata: Metadata = {
留了import NotPermissions from "./not-permissions"; ，Metadata相关的干掉了

2024-04-10 08:51 UTC, Of-qinhai commented on package.json
> +    "use-debounce": "^10.0.0",
已换。非常的丝滑
import _ from "lodash-es";
 _.debounce(funct(),...)

2024-04-11 02:33 UTC, wuzhuzhu commented on app/(console)/console/payload/components/search.tsx
> +	}, 300);
magicnumber， debounce的间隔可以用常量管理

2024-04-11 02:49 UTC, wuzhuzhu commented on lib/fetch-helper.ts
> +	Xheader.getSetCookie();
这是取值，没有任何操作，直接删掉这行。
header原本自带cookie

2024-04-11 02:49 UTC, wuzhuzhu commented on lib/fetch-helper.ts
> +	Xheader.delete("Content-Length");
cookie相关是无效操作，直接删掉
contenttype应该使用时外传，这里理想情况（解决下面问题）只是在添加一个type，没有抽象必要

length的问题 ，只有在server action才会触发，是因为某些版本选用的node polifill引起，直接删掉并不是优雅的问题，也会带来附加问题。在这里处理不妥，这个看上线时间，如果来得及我会直接在fetchfromserver做临时修复。来不急就先这么上

2024-04-11 03:17 UTC, wuzhuzhu requested changes

2024-04-11 03:17 UTC, wuzhuzhu commented on app/(console)/console/layout.tsx
> +					<Toaster />
Toaster给重复了，去掉

2024-04-11 03:17 UTC, wuzhuzhu commented on app/(console)/console/layout.tsx
> +				<Providers session={session}>
权限检查在layout不是不能做，各有利弊。但是按目前设计来讲 是集中到middleware的。不过改动middleware要慎重，目前来不及了，这里记一个todo

2024-04-11 03:47 UTC, Of-qinhai commented on app/(console)/console/payload/components/search.tsx
> +	}, 300);
/lib/constans/config.ts  add DEBOUNCE_TIME=300

2024-04-11 03:47 UTC, Of-qinhai commented on lib/fetch-helper.ts
> +	Xheader.delete("Content-Length");
已干掉Xheader.getSetCookie();

2024-04-11 03:50 UTC, Of-qinhai commented on app/(console)/console/layout.tsx
> +					<Toaster />
不给不行啊，完全独立于2个不同的Layout 里，非重复的。

2024-04-11 06:44 UTC, wuzhuzhu requested changes

2024-04-11 06:44 UTC, wuzhuzhu commented on app/(console)/console/not-permissions.tsx
> +
和设计对齐这页的样式。console内部的没关系，报错页会给客户看到的

2024-04-11 06:44 UTC, wuzhuzhu commented on app/(console)/console/payload/[payloadId]/components/preview-form.tsx
> +        <div className="schema-form px-8 w-full py-4 bg-muted">
注意下这个组件，其实组件的wrapper样式，尤其margin，padding一类。最佳实践是在组件外部控制。（想像一下组件库里的组件如何设计）
再看下这个组件本身，其实只做了一件事就是封装了一个wrapper样式
所以，我建议这个组件不拆分，直接在父级调用Form

不强制修改

2024-04-11 06:44 UTC, wuzhuzhu commented on app/(console)/console/payload/[payloadId]/page.tsx
> +            headers: getAuthHeader(),
目前看至少所有使用 getAuthHeader的均为无效操作，应该直接去掉
getAuthJsonHeader的看情况，即使是post+body其实直接用fetchfromserver也没问题，唯独server action里面会出现length问题。
不在server action里的都可以去掉

fetchFromServer('api/v1/...', {next: {revalidate: 常量}})

2024-04-11 06:44 UTC, wuzhuzhu commented on app/(console)/console/payload/components/cell-action.tsx
> +import { AlertModal } from "@/components/console/modal";
是不是各个模块的cell action 其实可以一个组件

2024-04-11 06:44 UTC, wuzhuzhu commented on app/(console)/console/payload/components/client.tsx
> +            <Separator />
记得干掉

2024-04-11 06:44 UTC, wuzhuzhu commented on app/(console)/console/payload/page.tsx
> +		headers: getAuthHeader(),
mark

2024-04-11 06:44 UTC, wuzhuzhu commented on app/(console)/console/payload/page.tsx
> +			headers: getAuthHeader(),
mark

2024-04-11 06:44 UTC, wuzhuzhu commented on app/(console)/console/playground/[playgroundId]/components/playground-form.tsx
> +                        duration: 1500
magic number，const管理

2024-04-11 06:44 UTC, wuzhuzhu commented on app/(console)/console/playground/[playgroundId]/components/playground-form.tsx
> +                        duration: 1500
mark

2024-04-11 06:44 UTC, wuzhuzhu commented on app/(console)/console/playground/[playgroundId]/components/playground-form.tsx
> +                        duration: 1500
mark

2024-04-11 06:44 UTC, wuzhuzhu commented on app/(console)/console/playground/[playgroundId]/components/playground-form.tsx
> +                        duration: 1500
mark

2024-04-11 06:44 UTC, wuzhuzhu commented on app/(console)/console/playground/[playgroundId]/components/playground-form.tsx
> +                duration: 1500
mark

2024-04-11 06:44 UTC, wuzhuzhu commented on app/(console)/console/playground/[playgroundId]/components/playground-form.tsx
> +            <Separator />
mark

2024-04-11 06:44 UTC, wuzhuzhu commented on app/(console)/console/playground/components/cell-action.tsx
> +"use client";
mark

2024-04-11 06:44 UTC, wuzhuzhu commented on app/(console)/console/playground/components/client.tsx
> +            <Separator />
mark

2024-04-11 06:44 UTC, wuzhuzhu commented on app/(console)/console/playground/page.tsx
> +                revalidate: 30,
mark

2024-04-11 06:44 UTC, wuzhuzhu commented on app/(console)/console/users/[userId]/components/user-form.tsx
> +    const action = "Save changes";
这个我不是很理解

2024-04-11 06:44 UTC, wuzhuzhu commented on app/(console)/console/users/components/cell-action.tsx
> +        const res = await fetch(`/api/console/users?userId=${data.id}`, {
fetchfromclient

2024-04-11 06:44 UTC, wuzhuzhu commented on app/(console)/console/users/components/cell-action.tsx
> +                duration: 1500
mark

2024-04-11 06:44 UTC, wuzhuzhu commented on app/(console)/console/users/components/cell-action.tsx
> +                duration: 1500
mark

2024-04-11 06:44 UTC, wuzhuzhu commented on app/(console)/console/users/components/cell-action.tsx
> +        router.push("/console/users", undefined);
为何传一个undifined?

2024-04-11 07:05 UTC, wuzhuzhu commented on components/dashboard/payload/page.tsx
> +
payloads即可吧，就算加all也是all payloads

2024-04-11 07:09 UTC, Of-qinhai commented on app/(console)/console/payload/[payloadId]/components/preview-form.tsx
> +        <div className="schema-form px-8 w-full py-4 bg-muted">
原页面代码太多了，这个非必要先不改。

2024-04-11 07:11 UTC, wuzhuzhu commented on components/dashboard/layout/providers.tsx
> +    <>
多余标签

2024-04-11 07:13 UTC, wuzhuzhu commented on components/dashboard/layout/providers.tsx
> +      <SessionProvider session={session}>{children}</SessionProvider>
在各个组件重复拿从执行效率上讲是一样的

2024-04-11 07:17 UTC, wuzhuzhu commented on components/dashboard/checkbox/index.tsx
这是定制了shadcn的checkbox吗？感觉复制了checkbox的安装文件/ui
不能使用classname和一些viaration进行设置吗

2024-04-11 07:19 UTC, wuzhuzhu commented on components/auth/nav-list.tsx
>  	DropdownMenuShortcut,
“在用数据的距离最近的地方拿数据”

2024-04-11 07:20 UTC, wuzhuzhu commented on app/layout.tsx
> -		<html lang="en">
哎？原来是这样吗？如果是可以 不是好像不用加

2024-04-11 07:22 UTC, wuzhuzhu commented on app/api/dashboard/users/route.ts
这里用route handler而不是直接发请求的原因是？
客户端组件是可以调用server action的，之前分享讲过 route handler大部分情况使用不到的 一般来说是给别的项目跨项目使用 这样他们用不了sever action

2024-04-11 07:24 UTC, Of-qinhai commented on app/(console)/console/payload/components/cell-action.tsx
> +import { AlertModal } from "@/components/console/modal";
我的建议是不要封装成一个组件，官方的示例也没有封装成一个，如果封装成了一个cell action 里包含的操作或者外部的依赖，会导致传入的东西过多。

2024-04-11 07:25 UTC, wuzhuzhu commented on app/(dashboard)/dashboard/users/page.tsx
> +	const { data }: { data: UserPage } = await getUserPage(
更好的方式是给params命名
{
current, pageSize, name, email
}
这样调用的时候有点儿看不懂（有ts会好点儿），而且中间安插可选也会不好（比如中间某个参数变成可选了，你还得调动顺序，调动完了之后还得改所有用它的地方）

2024-04-11 07:27 UTC, wuzhuzhu commented on app/(dashboard)/dashboard/users/components/search.tsx
> +import _ from "lodash-es";
增大包体积。
使用-es就是因为是esm
用什么引用什么 : import {debounce} from 'lodash-es'

2024-04-11 07:27 UTC, wuzhuzhu commented on app/(dashboard)/dashboard/users/components/client.tsx
> +			<Separator />
mark

2024-04-11 07:27 UTC, wuzhuzhu commented on app/(dashboard)/dashboard/users/[userId]/components/user-form.tsx
> +						duration: 1500,
duration可以统一改下const

2024-04-11 07:28 UTC, wuzhuzhu commented on app/(dashboard)/dashboard/users/[userId]/components/user-form.tsx
> +	const action = "Save changes";
这个不理解，命名一个常量然后后面引用一次

2024-04-11 07:34 UTC, Of-qinhai commented on app/(console)/console/inference/components/client.tsx
> +            <Separator />
表格只有顶部边框，现在的边框是滚动区域组件给的，去掉滚动？

2024-04-11 07:39 UTC, wuzhuzhu commented on app/(dashboard)/dashboard/playground/components/client.tsx
> +			<Separator />
mark

2024-04-11 07:43 UTC, wuzhuzhu commented on app/(dashboard)/dashboard/payload/components/client.tsx
> +			<Separator />
mark

2024-04-11 07:43 UTC, wuzhuzhu commented on app/(dashboard)/dashboard/payload/[payloadId]/components/error.tsx
和设计对一下样式

2024-04-11 07:44 UTC, merged

2024-04-11 08:02 UTC, Of-qinhai commented on components/dashboard/playground/page.tsx
> +export default function PlaygroundSelect({ data, defaultId, onValueChange }: { data: Playground[], defaultId?: string, onValueChange: (value: string) => void }) {
已改为index.tsx

2024-04-11 08:07 UTC, Of-qinhai commented on app/(console)/console/users/components/cell-action.tsx
> +        const res = await fetch(`/api/console/users?userId=${data.id}`, {
不行，这是delete，走你那个会报错。

2024-04-11 08:29 UTC, Of-qinhai commented on app/(console)/console/users/components/cell-action.tsx
> +        router.push("/console/users", undefined);
手误

2024-04-12 02:02 UTC, Of-qinhai commented on app/layout.tsx
> -		<html lang="en">
没看懂，是指我加的suppressHydrationWarning ？这个？如果是这个的话，原先就没有，我加这个是为了解决那个
 <ThemeProvider attribute="class" defaultTheme="system" enableSystem> */}   这里加的class的警告，服务端组件这个会报warning，既然这个已经干掉了，所以我加的suppressHydrationWarning  就干掉了。

2024-04-12 02:08 UTC, Of-qinhai commented on components/auth/nav-list.tsx
>  	DropdownMenuShortcut,
这个就没必要吧，nav-list 作为user-nav的子组件，从user-nav.tsx我觉得是比较合理的，而且user-nav是一个服务端组件，nav-list是一个客户端组件。

2024-04-12 02:13 UTC, Of-qinhai commented on components/dashboard/checkbox/index.tsx
是的，因为前端ui组件库样式已经做了覆盖，我引的组件样式都是覆盖后的，dashboard 里引用的shadui的组件都收到了影响，因时间紧凑，怕改动影响到前端的动态表单组件样式，所以单独复制安装文件/ui。后续有空闲的时候再整理。

2024-04-12 02:18 UTC, Of-qinhai commented on components/dashboard/data-table/index.tsx
> +			<ScrollArea className="rounded-md border h-[calc(80vh-100px)]">
做的时候觉得这个好看就用了。原有的样式很难看。有性能问题再说。

2024-04-12 03:46 UTC, Of-qinhai commented on components/dashboard/layout/providers.tsx
> +      <SessionProvider session={session}>{children}</SessionProvider>
已物理删除

2024-04-12 05:41 UTC, Of-qinhai commented on app/api/dashboard/users/route.ts
使用到了prismaClient的操作，不能在client 组件里使用哦，这里使用了封装的AlterModal 组件，在confirm里调用server ation ，分拆成本太大。

2024-04-12 05:41 UTC, Of-qinhai commented on components/dashboard/layout/providers.tsx
> +    <>
已物理删除

2024-04-12 05:45 UTC, Of-qinhai commented on components/dashboard/modal/modal.tsx
> +    return (
因为shadUi没有alertModal这样的组件，所以临时写了一个，当产品有一天提出来需要使用别的modal的要求，我会再基于新的需求再封装一个，这个本来的意义只是一个confirm，可能文件名称让你产生了误解。这个在没开始做的时候，没人知道产品要的是啥样的，dashboard 的定义已经使用人群，我现在也不太清楚。留点发挥空间？

2024-04-12 05:50 UTC, Of-qinhai commented on components/dashboard/pagination/index.tsx
这个只是基于你修改的分页做的提取，我做到user的时候才发现拿的是全量的，这个终归是需要重构的。暂时先这样。共享层级有用到再说，无非就是一个目录的存放的问题，只是现在从components/dashboard/pagination/index.tsx/
引用罢了，这不是一个成熟高可用的组件，还有优化的空间，至于后面谁优化，谁来实现按页码来分页，我觉得可以那个时候再考虑这个问题。

2024-04-12 05:52 UTC, Of-qinhai commented on app/(console)/console/playground/components/cell-action.tsx
> +"use client";
？